server:
  port: 8080

spring:
  application:
    name: films
  datasource:
    url: jdbc:postgresql://localhost:5432/films
    username: films_user
    password: films_pass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

app:
  kinopoisk:
    base-url: https://kinopoiskapiunofficial.tech
    api-key: ${KINOPOISK_API_KEY}
  activemq:
    queues:
      grabbed-films: grabbed.films.queue